source "https://rubygems.org"

gem "github-pages", group: :jekyll_plugins

# Optional: Add any plugins you use explicitly
# group :jekyll_plugins do
#   gem "jekyll-feed"
#   gem "jekyll-seo-tag"
# end